name: Action Sample

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python python-sample.py
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: test.csv
      - name: git setting
        run: |
          git config --local user.email "ikuo-kobayashi@jreast.co.jp"
          git config --local user.name "ikuo-kobayashi"
      - name: Commit files
        run: |
          git add .
          git commit -m "Add csv" -a
          git pull
          git push origin main
